using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NexusERP.Application.Interfaces.Services;
using NexusERP.Domain.Entities;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;


namespace NexusERP.Infrastructure.Services
{
    public class PdfExportService : IPdfExportService
    {
        public void GenerateInvoice(InventoryTransaction model, string filePath)
        {
            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(50);
                    page.Size(PageSizes.A4);
                    page.DefaultTextStyle(x => x.FontSize(11).FontFamily(Fonts.Verdana));

                    // --- HEADER ---
                    page.Header().Row(row =>
                    {
                        row.RelativeItem().Column(col =>
                        {
                            col.Item().Text("TRANSACTION INVOICE").FontSize(22).SemiBold().FontColor(Colors.Blue.Medium);
                            col.Item().Text($"Transaction ID: #{model.TransactionId}").FontSize(12);
                            col.Item().Text($"Date: {model.CreatedAt:MMMM dd, yyyy HH:mm}");
                        });

                        row.RelativeItem().AlignRight().Column(col =>
                        {
                            col.Item().Text("SUPPLIER INFORMATION").SemiBold();
                            col.Item().Text(model.SupplierName).FontSize(14).Medium();
                        });
                    });

                    // --- CONTENT ---
                    page.Content().PaddingVertical(30).Column(col =>
                    {
                        col.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(3); // Description
                                columns.RelativeColumn();  // Type
                                columns.RelativeColumn();  // Qty
                                columns.RelativeColumn();  // Amount
                            });

                            table.Header(header =>
                            {
                                IContainer CellStyle(IContainer c) =>
                                    c.DefaultTextStyle(x => x.SemiBold()).PaddingVertical(5).BorderBottom(1);

                                header.Cell().Element(CellStyle).Text("Product Description");
                                header.Cell().Element(CellStyle).Text("Type");
                                header.Cell().Element(CellStyle).Text("Quantity");
                                header.Cell().Element(CellStyle).Text("Total");
                            });

                            IContainer ValueStyle(IContainer c) => c.PaddingVertical(10);

                            table.Cell().Element(ValueStyle).Text(model.ProductName);
                            table.Cell().Element(ValueStyle).Text(model.TransactionType.ToString());
                            table.Cell().Element(ValueStyle).Text(model.Quantity.ToString());
                            table.Cell().Element(ValueStyle).Text($"{model.TotalAmount:C2}");
                        });

                        col.Item().PaddingTop(20).AlignRight().Text($"Total Amount: {model.TotalAmount:C2}").FontSize(16).SemiBold();
                    });

                    page.Footer().AlignCenter().Text(x => {
                        x.Span("Generated by Product Inventory Manager | Page ");
                        x.CurrentPageNumber();
                    });
                });
            }).GeneratePdf(filePath);
        }
    }
}
